[categories]
LANGUAGES=java|python|rust|javascript
; database management system
DBMS=mongodb|mysql|postgresql
FONTS=JetBrains_Mono|Cascadia_Mono|Fira_Code
CLI=make|wsl|gitbash|termius
CODE=vscode
OPS=git|docker
OTHER=bruno|compass|pgadmin|mysql_wb|nodejs
; packet management system
PMS=uv|mvn|bun

; ------------------------------------------------------------
; THIS IS THE DEFAULT VERSION OF THE TOOLS
; ------------------------------------------------------------

[categories.languages.versions]
languages.java=21
languages.python=3.14
languages.rust=1.95.0
languages.javascript=ES2025

[categories.dbms.versions]
dbms.mongodb=8.0
dbms.mysql=8.0
dbms.postgresql=18

[categories.cli.versions]
cli.wsl=2

[categories.other.versions]
other.bruno=3.3.0
other.compass=1.49.5
other.pgadmin=9.14
other.mysql_wb=8.0.47
other.nodejs=v25.9.0

[categories.pms.versions]
pms.mvn=3.9.15

; SPECIFIC VSCODE

[categories.code.vscode.plugins]
copilot=github.copilot,github.copilot-chat
raythis=goopware.raythis
rust=1yib.rust-bundle
python=ms-python.debugpy,ms-python.isort,ms-python.python,ms-python.vscode-pylance,ms-python.vscode-python-envs
misc=pkief.material-icon-theme,tomoki1207.pdf,vivaxy.vscode-conventional-commits,repreng.csv
java=vscjava.vscode-java-pack
sonar=sonarsource.sonarlint-vscode