spring.shell.interactive.enabled=true
spring.shell.history.enabled=true
spring.shell.history.name=.macfg-history

logging.level.root=WARN
logging.level.com.macfg=INFO
logging.level.org.springframework.shell=WARN

spring.main.banner-mode=off
# spring.banner.location=classpath:banner.txt