[links]
BUSYBOX=https://frippery.org/files/busybox/busybox.exe
GIT_BUSYBOX=https://github.com/git-for-windows/git/releases/download/v2.44.0.windows.1/MinGit-2.44.0-64-bit.zip
JAVA=https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.zip
PYTHON=https://www.python.org/ftp/python/3.14.3/python-3.14.3-embed-amd64.zip
VSCODE=https://update.code.visualstudio.com/latest/win32-x64-archive/stable
BRUNO=https://github.com/usebruno/bruno/releases/download/v1.38.0/bruno_1.38.0_x64_win.zip
# Polices (Direct Downloads)
FONT_JB=https://github.com/JetBrains/JetBrainsMono/releases/download/v2.304/JetBrainsMono-2.304.zip