name: main pipeline

on:
  push:
    branches: [ "main", "develop", "feature/**", "fix/**", "release/**" ]
  pull_request:
    branches: [ "main", "develop", "feature/**", "fix/**", "release/**" ]

jobs:
  build-task:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  promote-task:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-task
    uses: ./.github/workflows/promote.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit